### ISSUE TITLE
Doesn't compile with --debug: `elm: Map.!: given key is not an element in the map`

### ISSUE THREAD

**Issue by runarfu** [CurrySoftware/elm-datepicker#15]
I'm sorry that I open an issue for this here, as it's not really a problem with this library - it's in the compiler. However, if the bug isn't fixed any time soon, I would love to see a workaround if that's possible. There are several open issues in the compiler repo, one of them is https://github.com/elm/compiler/issues/1817.

**Comment by JDemler** [comment]
Sorry, I can not reproduce...

```
$ rm -r ../elm-stuff/
$ make
cd .. && elm make examples/simple/Simple.elm --output=examples/simple/simple.js --debug
Dependencies loaded from local cache.
Dependencies ready!                
Success! Compiled 3 modules.                                         
cd .. && elm make examples/bootstrap/Bootstrap.elm --output=examples/bootstrap/bootstrap.js --debug
Success! Compiled 1 module.                                          
cd .. && elm make examples/range/Range.elm --output=examples/range/range.js --debug
Success! Compiled 1 module.                                          
cd .. && elm make examples/simple-nightwatch/SimpleNightwatch.elm --output=examples/simple-nightwatch/simple-nightwatch.js --debug
Success! Compiled 1 module.                      
```

Is this a platform problem or a flaky bug? Is it a problem in your codebase?

**Comment by runarfu** [comment]
I've reproduced the bug with two minimal examples in Ellie, where the first one compiles (but ignores the message from the datepicker), and the second one doesn't. The second one is supposed to route the message and ignore it (just to demonstrate that this is where the compiler starts having troubles). The error is different in Ellie, but it still doesn't compile.

https://ellie-app.com/3WdDvCRxtT5a1 (compiling)
https://ellie-app.com/3WdF37WL6d7a1 (not compiling)

**Comment by runarfu** [comment]
In https://github.com/elm/compiler/issues/1753 there is this comment:
> Same problem here. Using a non-basic type in the `Msg` crashes the compiler with `--debug`.

which seems plausible in this case also.

**Comment by JDemler** [comment]
If I understand this problem, a workaround would imply changing `DatePicker.Msg` so that it does not include `Date` anymore...

This would break basically for every user of this library. So I do not think it is feasible.
It seems, that a common workaround is to include the source directly (in `elm.json` via the `source-directories`) instead of using it as a package.


Otherwise have a look at https://github.com/elm/compiler/issues/1852. Maybe the workaround there will help you. 

I realize this is not a very satisfying answer; but I am very reluctant to introduce a breaking change for a problem that will eventually be fixed upstream anyways.

**Comment by runarfu** [comment]
I agree with you, it's not a good idea to introduce a breaking change for this. The workaround seems like a perfect (temporary) solution, thank you! I'm closing this issue now, as it's (as already stated) not a problem with this library. Hopefully the compiler bug will be fixed soon, and we can use the library normally again. Thank you for your quick responses!
