### ISSUE TITLE
Manually input date not reflected in DateEvent

### ISSUE THREAD

**Issue by absynce** [CurrySoftware/elm-datepicker#20]
When manually changing the date via the text input, the `DateEvent` does not register it as updated. 
[Ellie (standard simple example with 3.0.1)](https://ellie-app.com/3WbsRpXXzJ5a1)
![datepicker-currysoftware-3 0 1-version-fails-manual-update](https://user-images.githubusercontent.com/289969/52981213-cf2c8d00-33a3-11e9-8d17-b2da99d9dbfb.gif)

This was working with the elm-community version.
[Ellie (former simple example from elm-community)](https://ellie-app.com/jGNHkN3rS5a1)
![datepicker-elm-community-version-updates-manual](https://user-images.githubusercontent.com/289969/52981241-000cc200-33a4-11e9-9a18-45ca6a0f9ec0.gif)

**Comment by martin-endress** [comment]
Thank you for submitting this issue. We will look into it!

**Comment by martin-endress** [comment]
The default `dateFormatter` does not match the default `parser` which only accepts `ISO 8601` dates. For now, the solution to your problem is changing either the default formatter or the default parser in the `defaultSettings`.
As mentioned in #19, changing either default value would break things and the issue is too small to justify a breaking change.
You may also use the `FailedInput Event` which is returned when the parser does not accept the given String.

We agree this is confusing and we will fix this in the next major update.

**Comment by absynce** [comment]
Thank you for the explanation and workaround! I read that issue but didn't see the connection. 😳 Hopefully the GIFs help other folks identify the symptoms.

**Comment by absynce** [comment]
Anyone coming here looking for a solution, a simple one is to change the `dateFormatter`:
```elm
settings : DatePicker.Settings
settings =
    { defaultSettings
        | dateFormatter = Date.format "yyyy-MM-dd"
    }
```

[Example Ellie](https://ellie-app.com/52MtB2PSkdva1)
