### ISSUE TITLE
Picking a date doesn't update the datepicker view

### ISSUE THREAD

**Issue by Ahrengot** [CurrySoftware/elm-datepicker#21]
Hi there!

The documentation for [pick](https://package.elm-lang.org/packages/CurrySoftware/elm-datepicker/3.0.1/DatePicker#pick) says that this will produce a message that does the following:

> • change the calendar focus
> • replace the input text with the new value
> • close the picker
> • update datepickerSettings (pick someDate) datepicker

But it seems that the calendar focus isn't being changed properly. When I click the datepicker after setting a new date with `pick` it will show the current month instead of the month for the picked date.

I set up an Ellie demonstrating it here: https://ellie-app.com/4TRnVQ863Tsa1 see the `GotTimeZone` branch of update where I pick the date after getting the timezone.

Looking at [the source code for `pick`](https://github.com/CurrySoftware/elm-datepicker/blob/master/src/DatePicker.elm#L325) it seems the the focus is being set to Nothing instead of the picked date, but if I manually pick a different date then the datepicker will remember the selected month the next time I open it.

**Comment by JDemler** [comment]
The underlying problem in your example is a race condition: 
![image](https://user-images.githubusercontent.com/12686782/53892207-24b39b80-402c-11e9-9964-0aca3a1d0da3.png)


First the `GotTimeZone` msg is fired, after that, the `CurrentDate` msg from the `DatePicker`.
If you comment out the `Cmd.map DatePickerMsg dpCmd` in your `init` everything works fine.

Focus in this `DatePicker` works like this: 

```
currentDate =
   focused |> maybeOr pickedDate |> Maybe.withDefault today
```
Or in human: If the internal state has a focus date, take that.
Otherwise check if there is a selected date from the user.
Otherwise use todays date.

So setting `focus` to `Nothing` on `Pick` is correct.
For your problem, I would recommend to use either: `initFromDate` or call the perform the `GotTimeZone` task after the `DatePicker` is fully initialized.

**Comment by JDemler** [comment]
I'm closing this. Please feel free to reopen if things are not clear!

**Comment by Ahrengot** [comment]
Ah, I see. That makes sense!

Thank you for taking the time to help out.

I updated the Ellie to work around this race condition for anyone else in the same boat. https://ellie-app.com/4Vhj2cm7Kjra1
